\set ON_ERROR_STOP on

create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;
create schema auth;
create function auth.uid()
returns uuid
language sql
stable
as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant execute on function auth.uid() to anon, authenticated;

create table public.emocion_general (
  id_emocion bigint generated by default as identity primary key,
  nombre_emocion text not null unique,
  valor_escala smallint not null unique check (valor_escala between 1 and 5)
);
insert into public.emocion_general (nombre_emocion, valor_escala)
values ('Muy mal', 1), ('Mal', 2), ('Neutro', 3), ('Bien', 4), ('Muy bien', 5);
alter table public.emocion_general enable row level security;
grant select on public.emocion_general to anon, authenticated;
create policy "public catalogs are readable" on public.emocion_general
  for select to anon, authenticated using (true);

create table public.estudiante (
  id_estudiante bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  rut text not null unique,
  primer_nombre text not null,
  segundo_nombre text,
  primer_apellido text not null,
  segundo_apellido text,
  numero_telefonico text,
  correo text
);
insert into public.estudiante (id_estudiante, auth_user_id, rut, primer_nombre, primer_apellido)
values
  (101, '10000000-0000-0000-0000-000000000001', 'RUT-TEST-1', 'Estudiante', 'Uno'),
  (202, '20000000-0000-0000-0000-000000000002', 'RUT-TEST-2', 'Estudiante', 'Dos');
alter table public.estudiante enable row level security;
grant select on public.estudiante to authenticated;
create policy "student reads own profile" on public.estudiante for select to authenticated
  using (auth_user_id = (select auth.uid()));

create table public.emocion_especifica (
  id_emocionesp bigint generated by default as identity primary key,
  nombre_emocionesp text not null,
  emocion_general_id_emocion bigint not null references public.emocion_general(id_emocion),
  unique (emocion_general_id_emocion, nombre_emocionesp),
  unique (id_emocionesp, emocion_general_id_emocion)
);
alter table public.emocion_especifica enable row level security;
grant select on public.emocion_especifica to anon, authenticated;
create policy "public catalogs are readable" on public.emocion_especifica
  for select to anon, authenticated using (true);

create table public.registro_emocional (
  id_registro bigint generated by default as identity primary key,
  fecha_hora timestamptz not null default now(),
  emocion_especifica_id_emocionesp bigint not null references public.emocion_especifica(id_emocionesp),
  estudiante_id_estudiante bigint not null references public.estudiante(id_estudiante),
  estudiante_carrera_id bigint
);
alter table public.registro_emocional enable row level security;
grant select on public.registro_emocional to authenticated;
grant insert (emocion_especifica_id_emocionesp, estudiante_id_estudiante,
  estudiante_carrera_id) on public.registro_emocional to authenticated;
create policy "student reads own emotional records" on public.registro_emocional for select to authenticated
  using (exists (
    select 1 from public.estudiante e
    where e.id_estudiante = estudiante_id_estudiante and e.auth_user_id = (select auth.uid())
  ));
create policy "student creates own emotional records" on public.registro_emocional for insert to authenticated
  with check (exists (
    select 1 from public.estudiante e
    where e.id_estudiante = estudiante_id_estudiante and e.auth_user_id = (select auth.uid())
  ));

create table public.aplicacion_test (
  id_aplicacion bigint generated by default as identity primary key,
  estudiante_id_estudiante bigint not null references public.estudiante(id_estudiante),
  unique (id_aplicacion, estudiante_id_estudiante)
);
create table public.alerta_bienestar (
  id_alerta bigint generated by default as identity primary key,
  estudiante_id_estudiante bigint not null references public.estudiante(id_estudiante),
  aplicacion_test_id_aplicacion bigint,
  constraint alerta_aplicacion_fk foreign key
    (aplicacion_test_id_aplicacion, estudiante_id_estudiante)
    references public.aplicacion_test(id_aplicacion, estudiante_id_estudiante)
);

\i /tmp/emotional_checkin_history.sql
\i /tmp/emotional_checkin_timestamp_grant.sql

select 1 / case when count(*) = 5 then 1 else 0 end
from public.emocion_especifica where nombre_emocionesp = 'Sin especificar';

set role authenticated;
set request.jwt.claim.sub = '10000000-0000-0000-0000-000000000001';
insert into public.registro_emocional
  (emocion_especifica_id_emocionesp, estudiante_id_estudiante, client_request_id, fecha_hora)
select es.id_emocionesp, 101, 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', '2026-09-28T03:00:00Z'
from public.emocion_especifica es
join public.emocion_general eg on eg.id_emocion = es.emocion_general_id_emocion
where eg.nombre_emocion = 'Bien' and es.nombre_emocionesp = 'Sin especificar'
on conflict (client_request_id) do nothing;
insert into public.registro_emocional
  (emocion_especifica_id_emocionesp, estudiante_id_estudiante, client_request_id, fecha_hora)
select es.id_emocionesp, 101, 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', '2026-09-28T03:00:00Z'
from public.emocion_especifica es
join public.emocion_general eg on eg.id_emocion = es.emocion_general_id_emocion
where eg.nombre_emocion = 'Bien' and es.nombre_emocionesp = 'Sin especificar'
on conflict (client_request_id) do nothing;
select 1 / case when count(*) = 1 then 1 else 0 end
from public.registro_emocional where estudiante_id_estudiante = 101;
reset role;

set role authenticated;
set request.jwt.claim.sub = '20000000-0000-0000-0000-000000000002';
insert into public.registro_emocional
  (emocion_especifica_id_emocionesp, estudiante_id_estudiante, client_request_id, fecha_hora)
select es.id_emocionesp, 202, 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', '2026-09-28T03:00:00Z'
from public.emocion_especifica es
join public.emocion_general eg on eg.id_emocion = es.emocion_general_id_emocion
where eg.nombre_emocion = 'Mal' and es.nombre_emocionesp = 'Sin especificar';
do $$
declare
  v_specific_emotion_id bigint;
begin
  select es.id_emocionesp into v_specific_emotion_id
  from public.emocion_especifica es
  join public.emocion_general eg on eg.id_emocion = es.emocion_general_id_emocion
  where eg.nombre_emocion = 'Bien' and es.nombre_emocionesp = 'Sin especificar';

  begin
    insert into public.registro_emocional
      (emocion_especifica_id_emocionesp, estudiante_id_estudiante, client_request_id)
    values (v_specific_emotion_id, 101, 'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
    raise exception 'RLS permitió insertar para otra persona';
  exception when insufficient_privilege then
    null;
  end;
end;
$$;
select 1 / case when count(*) = 1 then 1 else 0 end from public.registro_emocional;
delete from public.registro_emocional where estudiante_id_estudiante = 101;
select 1 / case when count(*) = 1 then 1 else 0 end from public.registro_emocional;
delete from public.registro_emocional where estudiante_id_estudiante = 202;
select 1 / case when count(*) = 0 then 1 else 0 end from public.registro_emocional;
reset role;

insert into public.registro_emocional
  (emocion_especifica_id_emocionesp, estudiante_id_estudiante)
select es.id_emocionesp, 101
from public.emocion_especifica es
join public.emocion_general eg on eg.id_emocion = es.emocion_general_id_emocion
where eg.nombre_emocion = 'Bien' and es.nombre_emocionesp = 'Sin especificar';
insert into public.aplicacion_test (estudiante_id_estudiante) values (101)
returning id_aplicacion \gset
insert into public.alerta_bienestar (estudiante_id_estudiante, aplicacion_test_id_aplicacion)
values (101, :id_aplicacion);

set role service_role;
select public.erase_student_personal_data('10000000-0000-0000-0000-000000000001');
reset role;

select 1 / case when not exists (
  select 1 from public.estudiante
  where auth_user_id = '10000000-0000-0000-0000-000000000001'
     or rut = 'RUT-TEST-1'
) then 1 else 0 end;
select 1 / case when not exists (
  select 1
  from public.registro_emocional r
  where r.estudiante_id_estudiante = 101
) then 1 else 0 end;
select 1 / case when not exists (
  select 1 from public.alerta_bienestar where estudiante_id_estudiante = 101
) then 1 else 0 end;
select 1 / case when not exists (
  select 1 from public.aplicacion_test where estudiante_id_estudiante = 101
) then 1 else 0 end;
select 1 / case when not has_function_privilege(
  'authenticated', 'public.erase_student_personal_data(uuid)', 'EXECUTE'
) and has_function_privilege(
  'service_role', 'public.erase_student_personal_data(uuid)', 'EXECUTE'
) then 1 else 0 end;