begin;
alter table public.test_catalogo enable row level security;
alter table public.evento_institucional enable row level security;
revoke all on public.test_catalogo,public.evento_institucional from public,anon,authenticated;
grant select on public.test_catalogo,public.evento_institucional to anon,authenticated;
create policy catalog_published on public.test_catalogo for select to anon,authenticated using(exists(select 1 from public.test_bienestar t where t.catalog_id=test_catalogo.catalog_id and t.publication_status='published'));
create policy event_published on public.evento_institucional for select to anon,authenticated using(published_at is not null);
drop policy "public catalogs are readable" on public.test_bienestar;
drop policy "public catalogs are readable" on public.test_resultado_nivel;
drop policy "public catalogs are readable" on public.pregunta_test;
drop policy "public catalogs are readable" on public.opcion_respuesta;
drop policy "public catalogs are readable" on public.material_apoyo;
drop policy "public catalogs are readable" on public.material_emocion;
drop policy "public catalogs are readable" on public.material_test;
create policy version_published on public.test_bienestar for select to anon,authenticated using(publication_status='published');
create policy level_published on public.test_resultado_nivel for select to anon,authenticated using(exists(select 1 from public.test_bienestar t where t.id_test=test_resultado_nivel.test_id and t.publication_status='published'));
create policy question_published on public.pregunta_test for select to anon,authenticated using(exists(select 1 from public.test_bienestar t where t.id_test=pregunta_test.test_id and t.publication_status='published'));
create policy option_published on public.opcion_respuesta for select to anon,authenticated using(exists(select 1 from public.pregunta_test p join public.test_bienestar t on t.id_test=p.test_id where p.id_pregunta=opcion_respuesta.pregunta_test_id_pregunta and t.publication_status='published'));
create policy tip_published on public.material_apoyo for select to anon,authenticated using(publication_status='published' and is_active);
create policy tip_mood_published on public.material_emocion for select to anon,authenticated using(exists(select 1 from public.material_apoyo m where m.id_material=material_emocion.material_apoyo_id_material and m.publication_status='published' and m.is_active));
create policy tip_result_published on public.material_test for select to anon,authenticated using(exists(select 1 from public.material_apoyo m join public.test_bienestar t on t.id_test=material_test.test_id where m.id_material=material_test.material_apoyo_id_material and m.publication_status='published' and m.is_active and t.publication_status='published'));
grant select,insert,update,delete on public.test_catalogo,public.test_bienestar,public.pregunta_test,public.opcion_respuesta,public.test_resultado_nivel,public.evento_institucional,public.material_apoyo,public.material_emocion,public.material_test to service_role;
grant usage on sequence public.test_bienestar_id_test_seq,public.pregunta_test_id_pregunta_seq,public.opcion_respuesta_id_opcion_seq,public.material_apoyo_id_material_seq,public.material_emocion_id_materialemocion_seq,public.material_test_id_materialtest_seq to service_role;
grant select on public.emocion_general,public.carrera,public.sede,public.estudiante_carrera to service_role;
revoke all on public.estudiante from service_role;
grant select(id_estudiante,auth_user_id,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido) on public.estudiante to service_role;
grant select(id,email) on auth.users to service_role;
commit;
