import { StyleSheet } from 'react-native';

import { interFamily as font } from '@/shared/theme/typography';

/* ── Recursos de crisis: misma paleta cálida que el test, con tipografía Inter ── */
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#faf6ee',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
  },
  headerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1a2b44',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  headerAvatarText: {
    fontSize: 15,
    color: '#f5efdf',
    fontFamily: font.extraBold,
  },
  headerTitle: {
    fontSize: 20,
    color: '#1a2b44',
    fontFamily: font.extraBold,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#8a94a6',
    marginTop: 2,
    fontFamily: font.regular,
  },
  closeButton: {
    fontSize: 28,
    color: '#1a2b44',
    lineHeight: 28,
    fontFamily: font.semiBold,
  },
  crisisContainer: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  crisisHeroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f0ead9',
    padding: 18,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  crisisIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#fbf0cd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  crisisHeroText: {
    flex: 1,
    marginRight: 10,
  },
  crisisHeroTitle: {
    fontSize: 18,
    color: '#1a2b44',
    marginBottom: 6,
    fontFamily: font.extraBold,
  },
  crisisHeroDesc: {
    fontSize: 13,
    lineHeight: 20,
    color: '#7d8698',
    fontFamily: font.regular,
  },
  crisisSectionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f0ead9',
    padding: 20,
    marginBottom: 14,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  crisisSectionTitle: {
    fontSize: 17,
    color: '#1a2b44',
    marginBottom: 4,
    fontFamily: font.extraBold,
  },
  crisisSectionDesc: {
    fontSize: 13,
    lineHeight: 19,
    color: '#8a94a6',
    marginBottom: 14,
    fontFamily: font.regular,
  },
  crisisRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f0ead9',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  crisisRowIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fbf0cd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  crisisRowText: {
    flex: 1,
    marginRight: 8,
  },
  crisisRowTitle: {
    fontSize: 14,
    color: '#1a2b44',
    fontFamily: font.extraBold,
  },
  crisisRowPhone: {
    fontSize: 15,
    color: '#1a2b44',
    marginTop: 1,
    fontFamily: font.bold,
  },
  crisisRowDesc: {
    fontSize: 12,
    lineHeight: 17,
    color: '#8a94a6',
    marginTop: 1,
    fontFamily: font.regular,
  },
  crisisRowArrow: {
    fontSize: 18,
    color: '#1a2b44',
    fontFamily: font.bold,
  },
  programCard: {
    backgroundColor: '#fdf6dd',
    borderWidth: 1,
    borderColor: '#e3c766',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  programCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  programIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f5e3ac',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  programCardTitle: {
    flex: 1,
    fontSize: 15,
    color: '#1a2b44',
    fontFamily: font.extraBold,
  },
  programButton: {
    marginTop: 14,
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: 'center',
  },
  programButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: font.bold,
  },
  referralText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
    marginBottom: 12,
    fontFamily: font.regular,
  },
  resourceDesc: {
    fontSize: 12,
    lineHeight: 17,
    color: '#8a94a6',
    marginTop: 2,
    fontFamily: font.regular,
  },
  crisisDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  crisisDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e5dcc4',
  },
  crisisDividerText: {
    flexShrink: 1,
    fontSize: 10,
    color: '#a39a7e',
    letterSpacing: 0.8,
    textAlign: 'center',
    marginHorizontal: 10,
    fontFamily: font.bold,
  },
  outlineButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#1a2b44',
    borderRadius: 999,
    paddingVertical: 14,
    marginTop: 12,
  },
  outlineButtonText: {
    color: '#1a2b44',
    fontSize: 15,
    fontFamily: font.bold,
  },
});
