import { StyleSheet } from 'react-native';

import { fontFamily as font } from '@/shared/typography';

/* ── Test emocional: panel compacto para que pregunta, opciones y acción
   quepan en una sola pantalla sin scroll vertical ── */
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#faf6ee',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 8,
  },
  headerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1a2b44',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  headerAvatarText: {
    fontSize: 14,
    color: '#f5efdf',
    fontFamily: font.extraBold,
  },
  headerTitle: {
    fontSize: 17,
    color: '#1a2b44',
    fontFamily: font.extraBold,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#8a94a6',
    marginTop: 1,
    fontFamily: font.regular,
  },
  closeButton: {
    fontSize: 26,
    color: '#1a2b44',
    lineHeight: 26,
    fontFamily: font.semiBold,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingBottom: 100,
    justifyContent: 'center',
  },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#f0ead9',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressLabel: {
    fontSize: 10,
    color: '#98a2b3',
    letterSpacing: 0.8,
    fontFamily: font.bold,
  },
  progressValue: {
    fontSize: 12,
    color: '#1a2b44',
    fontFamily: font.bold,
  },
  progressBarTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: '#f3ecd4',
    overflow: 'hidden',
    marginBottom: 14,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#e9c258',
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  questionWrap: {
    flex: 1,
    marginRight: 8,
  },
  questionText: {
    fontSize: 17,
    color: '#1a2b44',
    lineHeight: 23,
    marginBottom: 4,
    fontFamily: font.extraBold,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#8a94a6',
    fontFamily: font.regular,
  },
  questionIllustration: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingTop: 2,
  },
  optionsList: {
    gap: 8,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f0ead9',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  optionButtonSelected: {
    backgroundColor: '#fdf6dd',
    borderColor: '#e3c766',
  },
  optionText: {
    fontSize: 14,
    color: '#1a2b44',
    fontFamily: font.semiBold,
  },
  optionTextSelected: {
    color: '#1a2b44',
  },
  selector: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#d8d2be',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorSelected: {
    backgroundColor: '#1a2b44',
    borderColor: '#1a2b44',
  },
  selectorInner: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  primaryButton: {
    marginTop: 14,
    backgroundColor: '#1a2b44',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: font.bold,
  },
  referralCard: {
    backgroundColor: '#fdf6dd',
    borderWidth: 1,
    borderColor: '#e3c766',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  referralTitle: {
    fontSize: 14,
    color: '#1a2b44',
    marginBottom: 6,
    fontFamily: font.extraBold,
  },
  referralText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
    marginBottom: 12,
    fontFamily: font.regular,
  },
  referralButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  referralButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: font.bold,
  },
  resultCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 22,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  resultHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultEyebrow: {
    fontSize: 11,
    color: '#64748b',
    letterSpacing: 1,
    fontFamily: font.bold,
  },
  badgeChip: {
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeChipText: {
    color: '#f8fafc',
    fontSize: 10,
    fontFamily: font.extraBold,
  },
  resultTitle: {
    fontSize: 18,
    color: '#1a2b44',
    lineHeight: 24,
    marginBottom: 16,
    fontFamily: font.bold,
  },
  resultPercentBox: {
    backgroundColor: '#f3f6f8',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 18,
  },
  resultPercent: {
    fontSize: 32,
    color: '#1a2b44',
    fontFamily: font.extraBold,
  },
  resultPercentLabel: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
    fontFamily: font.regular,
  },
  resultMessage: {
    fontSize: 15,
    color: '#1a2b44',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: font.bold,
  },
  resultButtonsRow: {
    gap: 10,
  },
  acceptButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  acceptButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: font.bold,
  },
  rejectButton: {
    backgroundColor: '#edf2f7',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d8e0e8',
  },
  rejectButtonText: {
    color: '#1a2b44',
    fontSize: 15,
    fontFamily: font.bold,
  },
});
