import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#faf6ee',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
  },
  headerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1a2b44',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  headerAvatarText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#f5efdf',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a2b44',
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#8a94a6',
    marginTop: 2,
  },
  closeButton: {
    fontSize: 28,
    color: '#1a2b44',
    fontWeight: '600',
    lineHeight: 28,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingBottom: 120,
    justifyContent: 'center',
  },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f0ead9',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 22,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  progressLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#98a2b3',
    letterSpacing: 0.8,
  },
  progressValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a2b44',
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#f3ecd4',
    overflow: 'hidden',
    marginBottom: 22,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#e9c258',
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  questionWrap: {
    flex: 1,
    marginRight: 10,
  },
  questionText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a2b44',
    lineHeight: 28,
    marginBottom: 8,
  },
  helperText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#8a94a6',
  },
  questionIllustration: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingTop: 4,
  },
  optionsList: {
    gap: 12,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f0ead9',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  optionButtonSelected: {
    backgroundColor: '#fdf6dd',
    borderColor: '#e3c766',
  },
  optionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a2b44',
  },
  optionTextSelected: {
    color: '#1a2b44',
  },
  selector: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#d8d2be',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorSelected: {
    backgroundColor: '#1a2b44',
    borderColor: '#1a2b44',
  },
  selectorInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  primaryButton: {
    marginTop: 28,
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  referralCard: {
    backgroundColor: '#fdf6dd',
    borderWidth: 1,
    borderColor: '#e3c766',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  referralTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a2b44',
    marginBottom: 6,
  },
  referralText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
    marginBottom: 12,
  },
  referralButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  referralButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  resourceList: {
    gap: 10,
    marginTop: 18,
    marginBottom: 4,
  },
  resourceCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#f0ead9',
    padding: 16,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  resourcePhone: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a2b44',
    marginBottom: 4,
  },
  resourceName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a2b44',
  },
  resourceDesc: {
    fontSize: 12,
    lineHeight: 17,
    color: '#8a94a6',
    marginTop: 2,
  },
  resultCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 22,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  resultHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 1,
  },
  badgeChip: {
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeChipText: {
    color: '#f8fafc',
    fontSize: 10,
    fontWeight: '800',
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
    lineHeight: 24,
    marginBottom: 16,
  },
  resultPercentBox: {
    backgroundColor: '#f3f6f8',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 18,
  },
  resultPercent: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1a2b44',
  },
  resultPercentLabel: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  resultMessage: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a2b44',
    textAlign: 'center',
    marginBottom: 16,
  },
  resultButtonsRow: {
    gap: 10,
  },
  acceptButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  acceptButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  rejectButton: {
    backgroundColor: '#edf2f7',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d8e0e8',
  },
  rejectButtonText: {
    color: '#1a2b44',
    fontSize: 15,
    fontWeight: '700',
  },
  crisisContainer: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  crisisHeroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f0ead9',
    padding: 18,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  crisisIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#fbf0cd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  crisisHeroText: {
    flex: 1,
    marginRight: 10,
  },
  crisisHeroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a2b44',
    marginBottom: 6,
  },
  crisisHeroDesc: {
    fontSize: 13,
    lineHeight: 20,
    color: '#7d8698',
  },
  crisisSectionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f0ead9',
    padding: 20,
    marginBottom: 14,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  crisisSectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1a2b44',
    marginBottom: 4,
  },
  crisisSectionDesc: {
    fontSize: 13,
    lineHeight: 19,
    color: '#8a94a6',
    marginBottom: 14,
  },
  crisisRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f0ead9',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  crisisRowIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fbf0cd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  crisisRowText: {
    flex: 1,
    marginRight: 8,
  },
  crisisRowTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a2b44',
  },
  crisisRowPhone: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a2b44',
    marginTop: 1,
  },
  crisisRowDesc: {
    fontSize: 12,
    lineHeight: 17,
    color: '#8a94a6',
    marginTop: 1,
  },
  crisisRowArrow: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
  },
  programCard: {
    backgroundColor: '#fdf6dd',
    borderWidth: 1,
    borderColor: '#e3c766',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  programCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  programIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f5e3ac',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  programCardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: '#1a2b44',
  },
  programButton: {
    marginTop: 14,
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: 'center',
  },
  programButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  crisisDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  crisisDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e5dcc4',
  },
  crisisDividerText: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    color: '#a39a7e',
    letterSpacing: 0.8,
    textAlign: 'center',
    marginHorizontal: 10,
  },
  outlineButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#1a2b44',
    borderRadius: 999,
    paddingVertical: 14,
    marginTop: 12,
  },
  outlineButtonText: {
    color: '#1a2b44',
    fontSize: 15,
    fontWeight: '700',
  },
});
