import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f9f9f7',
  },
  scrollContent: {
    padding: 20,
    paddingTop: 24,
    paddingBottom: 40,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backArrow: {
    fontSize: 16,
    color: '#334155',
    fontWeight: 'bold',
  },
  topBarTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a2b44',
    letterSpacing: 1,
  },
  topBarSpacer: {
    width: 36,
  },
  welcomeCard: {
    backgroundColor: '#fbf6dc',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#f3e7a0',
    marginBottom: 14,
  },
  badgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3e7a0',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  badgeIcon: {
    fontSize: 12,
    marginRight: 4,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1a2b44',
  },
  welcomeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
  },
  welcomeSubtitle: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  communityBanner: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    marginBottom: 16,
  },
  communityIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  communityIcon: {
    fontSize: 20,
  },
  communityTextContainer: {
    flex: 1,
  },
  communityTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1a2b44',
  },
  communitySubtitle: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 1,
    lineHeight: 14,
  },
  formCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  inputGroup: {
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1a2b44',
    marginBottom: 6,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 12,
  },
  inputLeadingIcon: {
    fontSize: 14,
    color: '#94a3b8',
    marginRight: 8,
  },
  input: {
    flex: 1,
    height: 44,
    fontSize: 12,
    color: '#1e293b',
  },
  eyeButton: {
    padding: 6,
  },
  eyeIcon: {
    fontSize: 14,
  },
  strengthBox: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  strengthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  strengthLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
  },
  strengthStatus: {
    fontSize: 10,
    fontWeight: '700',
    color: '#10b981',
  },
  strengthBarBg: {
    width: '100%',
    height: 4,
    backgroundColor: '#e2e8f0',
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 8,
  },
  strengthBarFill: {
    height: '100%',
    backgroundColor: '#10b981',
  },
  reqGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  reqItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '48%',
    marginBottom: 4,
  },
  reqIcon: {
    fontSize: 11,
    color: '#94a3b8',
    marginRight: 4,
  },
  reqPassed: {
    color: '#10b981',
    fontWeight: 'bold',
  },
  reqText: {
    fontSize: 9,
    color: '#64748b',
  },
  reqPassedText: {
    color: '#10b981',
    fontWeight: '600',
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: 10,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    marginTop: 1,
  },
  checkboxActive: {
    backgroundColor: '#1a2b44',
    borderColor: '#1a2b44',
  },
  checkboxCheck: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  termsText: {
    flex: 1,
    fontSize: 10,
    color: '#64748b',
    lineHeight: 14,
  },
  primaryButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 14,
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    marginRight: 6,
  },
  buttonArrow: {
    color: '#ffffff',
    fontSize: 14,
  },
  footerContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  footerText: {
    fontSize: 12,
    color: '#64748b',
  },
  loginLink: {
    color: '#1a2b44',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
});
