import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#eef2f4',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
  },
  closeButton: {
    fontSize: 28,
    color: '#1a2b44',
    fontWeight: '600',
    lineHeight: 28,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingBottom: 120,
    justifyContent: 'center',
  },
  panel: {
    backgroundColor: '#f6f7f7',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#dfe7eb',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  progressLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.8,
  },
  progressValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a2b44',
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#dfe5ea',
    overflow: 'hidden',
    marginBottom: 20,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#1a2b44',
  },
  questionWrap: {
    marginBottom: 18,
  },
  questionText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
    lineHeight: 25,
    marginBottom: 8,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748b',
  },
  optionsList: {
    gap: 10,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f3f5f6',
    borderWidth: 1,
    borderColor: '#dfe5ea',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 15,
  },
  optionButtonSelected: {
    backgroundColor: '#f7f2dc',
    borderColor: '#d4b43c',
  },
  optionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a2b44',
  },
  optionTextSelected: {
    color: '#1a2b44',
  },
  selector: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#c9d2db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorSelected: {
    backgroundColor: '#1a2b44',
    borderColor: '#1a2b44',
  },
  selectorInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  primaryButton: {
    marginTop: 26,
    backgroundColor: '#1a2b44',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingBottom: 80,
  },
  loadingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#1a2b44',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  loadingOrb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1a2b44',
    marginBottom: 14,
    borderWidth: 2,
    borderColor: '#dfe7eb',
  },
  loadingTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1a2b44',
    marginBottom: 8,
  },
  loadingText: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
  },
  resultCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 22,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  resultHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 1,
  },
  badgeChip: {
    backgroundColor: '#1a2b44',
    borderRadius: 999,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeChipText: {
    color: '#f8fafc',
    fontSize: 10,
    fontWeight: '800',
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2b44',
    lineHeight: 24,
    marginBottom: 16,
  },
  resultEmotionPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 14,
    paddingVertical: 16,
    marginBottom: 18,
  },
  resultEmotionTextWrap: {
    flex: 1,
  },
  resultMoodBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#edf2f7',
    borderWidth: 1,
    borderColor: '#dfe7eb',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  resultMoodBadgeText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a2b44',
  },
  resultEmotionText: {
    fontSize: 25,
    fontWeight: '800',
    color: '#1a2b44',
  },
  resultEmotionSub: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 4,
    lineHeight: 16,
  },
  resultPercentBox: {
    backgroundColor: '#f3f6f8',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 18,
  },
  resultPercent: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1a2b44',
  },
  resultPercentLabel: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  resultMessage: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a2b44',
    textAlign: 'center',
    marginBottom: 16,
  },
  resultButtonsRow: {
    gap: 10,
  },
  acceptButton: {
    backgroundColor: '#1a2b44',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  acceptButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  rejectButton: {
    backgroundColor: '#edf2f7',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d8e0e8',
  },
  rejectButtonText: {
    color: '#1a2b44',
    fontSize: 15,
    fontWeight: '700',
  },
});
