import { StyleSheet } from 'react-native';

import { glassTokens } from '@/shared/components/Glass';
import { fontFamily as font } from '@/shared/theme/typography';

const cream = '#f3ecda';
const navy = '#1a2b44';
const yellow = '#f2c14e';
const textSecondary = '#8a8272';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: cream,
  },
  scrollContent: {
    padding: 20,
    paddingTop: 28,
    paddingBottom: 32,
  },
  eyebrow: {
    color: textSecondary,
    fontSize: 11,
    letterSpacing: 1,
    fontFamily: font.bold,
  },
  title: {
    color: navy,
    fontSize: 28,
    marginTop: 4,
    fontFamily: font.extraBold,
  },
  subtitle: {
    color: textSecondary,
    fontSize: 13,
    marginTop: 3,
    marginBottom: 22,
    fontFamily: font.regular,
  },
  weekCard: {
    padding: 15,
    marginBottom: 18,
  },
  weekTitle: {
    color: navy,
    fontSize: 12,
    fontFamily: font.extraBold,
  },
  weekHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  weekArrow: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(26, 43, 68, 0.07)',
  },
  weekArrowText: {
    color: navy,
    fontSize: 22,
    lineHeight: 25,
    fontFamily: font.bold,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayButton: {
    flex: 1,
    minHeight: 68,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginHorizontal: 2,
  },
  dayButtonSelected: {
    backgroundColor: navy,
  },
  dayButtonPast: {
    opacity: 0.4,
  },
  dayName: {
    color: textSecondary,
    fontSize: 9,
    fontFamily: font.bold,
  },
  dayNameSelected: {
    color: '#f9dd85',
  },
  dayNumber: {
    color: navy,
    fontSize: 18,
    marginTop: 3,
    fontFamily: font.extraBold,
  },
  dayNumberSelected: {
    color: '#ffffff',
  },
  dayTextPast: {
    color: '#a39b8b',
  },
  addButton: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: navy,
    borderRadius: 17,
    marginBottom: 25,
    ...glassTokens.shadow,
  },
  addButtonIcon: {
    color: yellow,
    fontSize: 23,
    marginRight: 9,
    marginTop: -2,
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: font.bold,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 11,
  },
  sectionTitle: {
    color: navy,
    fontSize: 18,
    fontFamily: font.extraBold,
  },
  count: {
    color: textSecondary,
    fontSize: 12,
    fontFamily: font.semiBold,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
    ...glassTokens.shadow,
  },
  activityTime: {
    width: 54,
    color: navy,
    fontSize: 13,
    paddingTop: 2,
    fontFamily: font.extraBold,
  },
  activityAccent: {
    width: 3,
    borderRadius: 2,
    backgroundColor: yellow,
    marginRight: 12,
  },
  activityAccentActive: {
    backgroundColor: '#10a875',
  },
  activityDetails: {
    flex: 1,
  },
  activityTitle: {
    color: navy,
    fontSize: 14,
    fontFamily: font.extraBold,
  },
  activitySubject: {
    color: textSecondary,
    fontSize: 12,
    marginTop: 3,
    fontFamily: font.semiBold,
  },
  activityNoSubject: {
    color: textSecondary,
    fontSize: 11,
    marginTop: 3,
    fontStyle: 'italic',
    fontFamily: font.regular,
  },
  inProgressLabel: {
    color: '#087a55',
    fontSize: 9,
    letterSpacing: 0.5,
    marginBottom: 3,
    fontFamily: font.extraBold,
  },
  deleteButton: {
    justifyContent: 'center',
    paddingLeft: 10,
    paddingVertical: 6,
  },
  deleteText: {
    color: '#9b3d33',
    fontSize: 11,
    fontFamily: font.bold,
  },
  emptyCard: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyIcon: {
    color: '#b8a66b',
    fontSize: 28,
    marginBottom: 8,
  },
  emptyTitle: {
    color: navy,
    fontSize: 15,
    textAlign: 'center',
    fontFamily: font.extraBold,
  },
  emptyText: {
    color: textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
    textAlign: 'center',
    fontFamily: font.regular,
  },
  statusMessage: {
    color: '#9b3d33',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
    marginBottom: 12,
    fontFamily: font.semiBold,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: 'rgba(18, 28, 43, 0.48)',
  },
  modalCard: {
    backgroundColor: cream,
    borderRadius: 24,
    padding: 22,
    maxHeight: '92%',
    ...glassTokens.shadow,
  },
  modalTitle: {
    color: navy,
    fontSize: 21,
    marginBottom: 4,
    fontFamily: font.extraBold,
  },
  modalSubtitle: {
    color: textSecondary,
    fontSize: 12,
    marginBottom: 18,
    fontFamily: font.regular,
  },
  formScroll: {
    flexShrink: 1,
  },
  formContent: {
    paddingBottom: 2,
  },
  fieldLabel: {
    color: navy,
    fontSize: 12,
    marginBottom: 6,
    fontFamily: font.bold,
  },
  input: {
    minHeight: 48,
    backgroundColor: '#ffffff',
    borderColor: 'rgba(26, 43, 68, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    color: navy,
    fontSize: 14,
    paddingHorizontal: 13,
    marginBottom: 13,
    fontFamily: font.regular,
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -3,
    marginBottom: 15,
  },
  optionChip: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(26, 43, 68, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 9,
    marginHorizontal: 3,
    marginBottom: 7,
  },
  optionChipSelected: {
    backgroundColor: navy,
    borderColor: navy,
  },
  optionChipDisabled: {
    backgroundColor: 'rgba(26, 43, 68, 0.04)',
    borderColor: 'rgba(26, 43, 68, 0.06)',
  },
  optionChipText: {
    color: navy,
    fontSize: 11,
    fontFamily: font.semiBold,
  },
  optionChipTextSelected: {
    color: '#ffffff',
    fontFamily: font.bold,
  },
  optionChipTextDisabled: {
    color: '#a39b8b',
  },
  datePickerButton: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(26, 43, 68, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  datePickerButtonText: {
    flex: 1,
  },
  datePickerValue: {
    color: navy,
    fontSize: 14,
    fontFamily: font.extraBold,
  },
  datePickerHint: {
    color: textSecondary,
    fontSize: 11,
    marginTop: 2,
    fontFamily: font.regular,
  },
  datePickerChevron: {
    color: navy,
    fontSize: 23,
    paddingLeft: 10,
    fontFamily: font.bold,
  },
  calendarPanel: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(26, 43, 68, 0.10)',
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    marginBottom: 16,
  },
  calendarMonthHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  calendarMonthArrow: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: 'rgba(26, 43, 68, 0.07)',
  },
  calendarMonthArrowText: {
    color: navy,
    fontSize: 23,
    lineHeight: 27,
    fontFamily: font.bold,
  },
  calendarMonthArrowDisabled: {
    color: '#c9c2b5',
  },
  calendarMonthTitle: {
    color: navy,
    fontSize: 15,
    textTransform: 'capitalize',
    fontFamily: font.extraBold,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 14,
  },
  calendarCell: {
    width: '14.2857%',
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarWeekday: {
    color: textSecondary,
    fontSize: 11,
    fontFamily: font.bold,
  },
  calendarDayButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
  },
  calendarDayButtonSelected: {
    backgroundColor: navy,
  },
  calendarDayButtonDisabled: {
    opacity: 0.35,
  },
  calendarDayText: {
    color: navy,
    fontSize: 12,
    fontFamily: font.semiBold,
  },
  calendarDayTextSelected: {
    color: '#ffffff',
    fontFamily: font.extraBold,
  },
  calendarDayTextDisabled: {
    color: textSecondary,
  },
  subjectOptions: {
    marginBottom: 10,
  },
  subjectRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(26, 43, 68, 0.10)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    marginBottom: 7,
  },
  radioOuter: {
    width: 19,
    height: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#a39b8b',
    borderRadius: 10,
    borderWidth: 1.5,
    marginRight: 10,
  },
  radioOuterSelected: {
    borderColor: navy,
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: navy,
  },
  subjectRowText: {
    color: navy,
    fontSize: 12,
    fontFamily: font.semiBold,
  },
  modalActions: {
    flexDirection: 'row',
    marginTop: 4,
  },
  cancelButton: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    marginRight: 8,
    backgroundColor: 'rgba(26, 43, 68, 0.08)',
  },
  cancelText: {
    color: navy,
    fontSize: 13,
    fontFamily: font.bold,
  },
  saveButton: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    marginLeft: 8,
    backgroundColor: navy,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveText: {
    color: '#ffffff',
    fontSize: 12,
    textAlign: 'center',
    paddingHorizontal: 4,
    fontFamily: font.bold,
  },
});
